language: cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository ppa:yavdr/main -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -y
  - sudo apt-get install libcxxtools-dev libtntdb-dev tntdb-sqlite4 libmagic-dev libav-tools gcc-4.8 g++-4.8 -y
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90;
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90;
  - sudo pip install cpp-coveralls
script:
  - ./autogen.sh
  - ./configure --enable-gcov --enable-tests
  - make test && make all
  - ./tests/functionality.sh
after_success:
  - coveralls --exclude ext --exclude tests --exclude src/config.h --exclude src/\*.hpp -r . -b . --gcov gcov-4.8
env:
  global:
   - secure: "JMsbxCr5mACs5jUOBdiu1dXV/9qN2boAR+ovmiuVlt9qYOgFevU6LGVgrrUcQxUGpBeEzcFk5/Rfcpm+4yhcOb5rUEtAxe8PLwPN53ISXAePs5W9FHaqBn6PoLXHpTQ2ePmGA66oaOscRVeocNkzqL77cl/XwCry4/8A+neFhh4="
addons:
  coverity_scan:
    project:
      name: "miska/tomovee"
      description: "Build submitted via Travis CI"
    notification_email: michal@hrusecky.net
    build_command_prepend: "./autogen.sh && ./configure --enable-gcov --enable-tests"
    build_command: "make all"
    branch_pattern: coverity_scan
