language: cpp
compiler:
  - gcc
before_install:
  - sudo pip install cpp-coveralls
  - sudo apt-get install libsqlite3-dev
script:
  - ./autogen.sh && ./configure --enable-gcov --enable-tests && make test
after_success:
  - coveralls --exclude ext --exclude tests --exclude src/config.h
