#include "catch/catch.hpp"
#include "lang_codes.h"

TEST_CASE( "Lang2Code works", "[helper][lang2code]" ) {
    SECTION("Getting it works") {
        const char* test = 
        "blabla Afar bla "
"blabla Abkhazian bla "
"blabla Achinese bla "
"blabla Acoli bla "
"blabla Adangme bla "
"blabla Adyghe; Adygei bla "
"blabla Afro-Asiatic languages bla "
"blabla Afrihili bla "
"blabla Afrikaans bla "
"blabla Ainu bla "
"blabla Akan bla "
"blabla Akkadian bla "
"blabla Albanian bla "
"blabla Aleut bla "
"blabla Algonquian languages bla "
"blabla Southern Altai bla "
"blabla Amharic bla "
"blabla English, Old (ca.450-1100) bla "
"blabla Angika bla "
"blabla Apache languages bla "
"blabla Arabic bla "
"blabla Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE) bla "
"blabla Aragonese bla "
"blabla Armenian bla "
"blabla Mapudungun; Mapuche bla "
"blabla Arapaho bla "
"blabla Artificial languages bla "
"blabla Arawak bla "
"blabla Assamese bla "
"blabla Asturian; Bable; Leonese; Asturleonese bla "
"blabla Athapascan languages bla "
"blabla Australian languages bla "
"blabla Avaric bla "
"blabla Avestan bla "
"blabla Awadhi bla "
"blabla Aymara bla "
"blabla Azerbaijani bla "
"blabla Banda languages bla "
"blabla Bamileke languages bla "
"blabla Bashkir bla "
"blabla Baluchi bla "
"blabla Bambara bla "
"blabla Balinese bla "
"blabla Basque bla "
"blabla Basa bla "
"blabla Baltic languages bla "
"blabla Beja; Bedawiyet bla "
"blabla Belarusian bla "
"blabla Bemba bla "
"blabla Bengali bla "
"blabla Berber languages bla "
"blabla Bhojpuri bla "
"blabla Bihari languages bla "
"blabla Bikol bla "
"blabla Bini; Edo bla "
"blabla Bislama bla "
"blabla Siksika bla "
"blabla Bantu (Other) bla "
"blabla Bosnian bla "
"blabla Braj bla "
"blabla Breton bla "
"blabla Batak languages bla "
"blabla Buriat bla "
"blabla Buginese bla "
"blabla Bulgarian bla "
"blabla Burmese bla "
"blabla Blin; Bilin bla "
"blabla Caddo bla "
"blabla Central American Indian languages bla "
"blabla Galibi Carib bla "
"blabla Catalan; Valencian bla "
"blabla Caucasian languages bla "
"blabla Cebuano bla "
"blabla Celtic languages bla "
"blabla Chamorro bla "
"blabla Chibcha bla "
"blabla Chechen bla "
"blabla Chagatai bla "
"blabla Chinese bla "
"blabla Chuukese bla "
"blabla Mari bla "
"blabla Chinook jargon bla "
"blabla Choctaw bla "
"blabla Chipewyan; Dene Suline bla "
"blabla Cherokee bla "
"blabla Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic bla "
"blabla Chuvash bla "
"blabla Cheyenne bla "
"blabla Chamic languages bla "
"blabla Coptic bla "
"blabla Cornish bla "
"blabla Corsican bla "
"blabla Creoles and pidgins, English based bla "
"blabla Creoles and pidgins, French-based  bla "
"blabla Creoles and pidgins, Portuguese-based  bla "
"blabla Cree bla "
"blabla Crimean Tatar; Crimean Turkish bla "
"blabla Creoles and pidgins  bla "
"blabla Kashubian bla "
"blabla Cushitic languages bla "
"blabla Czech bla "
"blabla Dakota bla "
"blabla Danish bla "
"blabla Dargwa bla "
"blabla Land Dayak languages bla "
"blabla Delaware bla "
"blabla Slave (Athapascan) bla "
"blabla Dogrib bla "
"blabla Dinka bla "
"blabla Divehi; Dhivehi; Maldivian bla "
"blabla Dogri bla "
"blabla Dravidian languages bla "
"blabla Lower Sorbian bla "
"blabla Duala bla "
"blabla Dutch, Middle (ca.1050-1350) bla "
"blabla Dutch; Flemish bla "
"blabla Dyula bla "
"blabla Dzongkha bla "
"blabla Efik bla "
"blabla Egyptian (Ancient) bla "
"blabla Ekajuk bla "
"blabla Elamite bla "
"blabla English bla "
"blabla English, Middle (1100-1500) bla "
"blabla Esperanto bla "
"blabla Estonian bla "
"blabla Ewe bla "
"blabla Ewondo bla "
"blabla Fang bla "
"blabla Faroese bla "
"blabla Fanti bla "
"blabla Fijian bla "
"blabla Filipino; Pilipino bla "
"blabla Finnish bla "
"blabla Finno-Ugrian languages bla "
"blabla Fon bla "
"blabla French bla "
"blabla French, Middle (ca.1400-1600) bla "
"blabla French, Old (842-ca.1400) bla "
"blabla Northern Frisian bla "
"blabla Eastern Frisian bla "
"blabla Western Frisian bla "
"blabla Fulah bla "
"blabla Friulian bla "
"blabla Ga bla "
"blabla Gayo bla "
"blabla Gbaya bla "
"blabla Germanic languages bla "
"blabla Georgian bla "
"blabla German bla "
"blabla Geez bla "
"blabla Gilbertese bla "
"blabla Gaelic; Scottish Gaelic bla "
"blabla Irish bla "
"blabla Galician bla "
"blabla Manx bla "
"blabla German, Middle High (ca.1050-1500) bla "
"blabla German, Old High (ca.750-1050) bla "
"blabla Gondi bla "
"blabla Gorontalo bla "
"blabla Gothic bla "
"blabla Grebo bla "
"blabla Greek, Ancient (to 1453) bla "
"blabla Greek, Modern (1453-) bla "
"blabla Guarani bla "
"blabla Swiss German; Alemannic; Alsatian bla "
"blabla Gujarati bla "
"blabla Gwich'in bla "
"blabla Haida bla "
"blabla Haitian; Haitian Creole bla "
"blabla Hausa bla "
"blabla Hawaiian bla "
"blabla Hebrew bla "
"blabla Herero bla "
"blabla Hiligaynon bla "
"blabla Himachali languages; Western Pahari languages bla "
"blabla Hindi bla "
"blabla Hittite bla "
"blabla Hmong; Mong bla "
"blabla Hiri Motu bla "
"blabla Croatian bla "
"blabla Upper Sorbian bla "
"blabla Hungarian bla "
"blabla Hupa bla "
"blabla Iban bla "
"blabla Igbo bla "
"blabla Icelandic bla "
"blabla Ido bla "
"blabla Sichuan Yi; Nuosu bla "
"blabla Ijo languages bla "
"blabla Inuktitut bla "
"blabla Interlingue; Occidental bla "
"blabla Iloko bla "
"blabla Interlingua (International Auxiliary Language Association) bla "
"blabla Indic languages bla "
"blabla Indonesian bla "
"blabla Indo-European languages bla "
"blabla Ingush bla "
"blabla Inupiaq bla "
"blabla Iranian languages bla "
"blabla Iroquoian languages bla "
"blabla Italian bla "
"blabla Javanese bla "
"blabla Lojban bla "
"blabla Japanese bla "
"blabla Judeo-Persian bla "
"blabla Judeo-Arabic bla "
"blabla Kara-Kalpak bla "
"blabla Kabyle bla "
"blabla Kachin; Jingpho bla "
"blabla Kalaallisut; Greenlandic bla "
"blabla Kamba bla "
"blabla Kannada bla "
"blabla Karen languages bla "
"blabla Kashmiri bla "
"blabla Kanuri bla "
"blabla Kawi bla "
"blabla Kazakh bla "
"blabla Kabardian bla "
"blabla Khasi bla "
"blabla Khoisan languages bla "
"blabla Central Khmer bla "
"blabla Khotanese; Sakan bla "
"blabla Kikuyu; Gikuyu bla "
"blabla Kinyarwanda bla "
"blabla Kirghiz; Kyrgyz bla "
"blabla Kimbundu bla "
"blabla Konkani bla "
"blabla Komi bla "
"blabla Kongo bla "
"blabla Korean bla "
"blabla Kosraean bla "
"blabla Kpelle bla "
"blabla Karachay-Balkar bla "
"blabla Karelian bla "
"blabla Kru languages bla "
"blabla Kurukh bla "
"blabla Kuanyama; Kwanyama bla "
"blabla Kumyk bla "
"blabla Kurdish bla "
"blabla Kutenai bla "
"blabla Ladino bla "
"blabla Lahnda bla "
"blabla Lamba bla "
"blabla Lao bla "
"blabla Latin bla "
"blabla Latvian bla "
"blabla Lezghian bla "
"blabla Limburgan; Limburger; Limburgish bla "
"blabla Lingala bla "
"blabla Lithuanian bla "
"blabla Mongo bla "
"blabla Lozi bla "
"blabla Luxembourgish; Letzeburgesch bla "
"blabla Luba-Lulua bla "
"blabla Luba-Katanga bla "
"blabla Ganda bla "
"blabla Luiseno bla "
"blabla Lunda bla "
"blabla Luo (Kenya and Tanzania) bla "
"blabla Lushai bla "
"blabla Macedonian bla "
"blabla Madurese bla "
"blabla Magahi bla "
"blabla Marshallese bla "
"blabla Maithili bla "
"blabla Makasar bla "
"blabla Malayalam bla "
"blabla Mandingo bla "
"blabla Maori bla "
"blabla Austronesian languages bla "
"blabla Marathi bla "
"blabla Masai bla "
"blabla Malay bla "
"blabla Moksha bla "
"blabla Mandar bla "
"blabla Mende bla "
"blabla Irish, Middle (900-1200) bla "
"blabla Mi'kmaq; Micmac bla "
"blabla Minangkabau bla "
"blabla Uncoded languages bla "
"blabla Mon-Khmer languages bla "
"blabla Malagasy bla "
"blabla Maltese bla "
"blabla Manchu bla "
"blabla Manipuri bla "
"blabla Manobo languages bla "
"blabla Mohawk bla "
"blabla Mongolian bla "
"blabla Mossi bla "
"blabla Multiple languages bla "
"blabla Munda languages bla "
"blabla Creek bla "
"blabla Mirandese bla "
"blabla Marwari bla "
"blabla Mayan languages bla "
"blabla Erzya bla "
"blabla Nahuatl languages bla "
"blabla North American Indian languages bla "
"blabla Neapolitan bla "
"blabla Nauru bla "
"blabla Navajo; Navaho bla "
"blabla Ndebele, South; South Ndebele bla "
"blabla Ndebele, North; North Ndebele bla "
"blabla Ndonga bla "
"blabla Low German; Low Saxon; German, Low; Saxon, Low bla "
"blabla Nepali bla "
"blabla Nepal Bhasa; Newari bla "
"blabla Nias bla "
"blabla Niger-Kordofanian languages bla "
"blabla Niuean bla "
"blabla Norwegian Nynorsk; Nynorsk, Norwegian bla "
"blabla Bokmål, Norwegian; Norwegian Bokmål bla "
"blabla Nogai bla "
"blabla Norse, Old bla "
"blabla Norwegian bla "
"blabla N'Ko bla "
"blabla Pedi; Sepedi; Northern Sotho bla "
"blabla Nubian languages bla "
"blabla Classical Newari; Old Newari; Classical Nepal Bhasa bla "
"blabla Chichewa; Chewa; Nyanja bla "
"blabla Nyamwezi bla "
"blabla Nyankole bla "
"blabla Nyoro bla "
"blabla Nzima bla "
"blabla Occitan (post 1500); Provençal bla "
"blabla Ojibwa bla "
"blabla Oriya bla "
"blabla Oromo bla "
"blabla Osage bla "
"blabla Ossetian; Ossetic bla "
"blabla Turkish, Ottoman (1500-1928) bla "
"blabla Otomian languages bla "
"blabla Papuan languages bla "
"blabla Pangasinan bla "
"blabla Pahlavi bla "
"blabla Pampanga; Kapampangan bla "
"blabla Panjabi; Punjabi bla "
"blabla Papiamento bla "
"blabla Palauan bla "
"blabla Persian, Old (ca.600-400 B.C.) bla "
"blabla Persian bla "
"blabla Philippine languages bla "
"blabla Phoenician bla "
"blabla Pali bla "
"blabla Polish bla "
"blabla Pohnpeian bla "
"blabla Portuguese bla "
"blabla Prakrit languages bla "
"blabla Provençal, Old (to 1500) bla "
"blabla Pushto; Pashto bla "
"blabla Reserved for local use bla "
"blabla Quechua bla "
"blabla Rajasthani bla "
"blabla Rapanui bla "
"blabla Rarotongan; Cook Islands Maori bla "
"blabla Romance languages bla "
"blabla Romansh bla "
"blabla Romany bla "
"blabla Romanian; Moldavian; Moldovan bla "
"blabla Rundi bla "
"blabla Aromanian; Arumanian; Macedo-Romanian bla "
"blabla Russian bla "
"blabla Sandawe bla "
"blabla Sango bla "
"blabla Yakut bla "
"blabla South American Indian (Other) bla "
"blabla Salishan languages bla "
"blabla Samaritan Aramaic bla "
"blabla Sanskrit bla "
"blabla Sasak bla "
"blabla Santali bla "
"blabla Sicilian bla "
"blabla Scots bla "
"blabla Selkup bla "
"blabla Semitic languages bla "
"blabla Irish, Old (to 900) bla "
"blabla Sign Languages bla "
"blabla Shan bla "
"blabla Sidamo bla "
"blabla Sinhala; Sinhalese bla "
"blabla Siouan languages bla "
"blabla Sino-Tibetan languages bla "
"blabla Slavic languages bla "
"blabla Slovak bla "
"blabla Slovenian bla "
"blabla Southern Sami bla "
"blabla Northern Sami bla "
"blabla Sami languages bla "
"blabla Lule Sami bla "
"blabla Inari Sami bla "
"blabla Samoan bla "
"blabla Skolt Sami bla "
"blabla Shona bla "
"blabla Sindhi bla "
"blabla Soninke bla "
"blabla Sogdian bla "
"blabla Somali bla "
"blabla Songhai languages bla "
"blabla Sotho, Southern bla "
"blabla Spanish; Castilian bla "
"blabla Sardinian bla "
"blabla Sranan Tongo bla "
"blabla Serbian bla "
"blabla Serer bla "
"blabla Nilo-Saharan languages bla "
"blabla Swati bla "
"blabla Sukuma bla "
"blabla Sundanese bla "
"blabla Susu bla "
"blabla Sumerian bla "
"blabla Swahili bla "
"blabla Swedish bla "
"blabla Classical Syriac bla "
"blabla Syriac bla "
"blabla Tahitian bla "
"blabla Tai languages bla "
"blabla Tamil bla "
"blabla Tatar bla "
"blabla Telugu bla "
"blabla Timne bla "
"blabla Tereno bla "
"blabla Tetum bla "
"blabla Tajik bla "
"blabla Tagalog bla "
"blabla Thai bla "
"blabla Tibetan bla "
"blabla Tigre bla "
"blabla Tigrinya bla "
"blabla Tiv bla "
"blabla Tokelau bla "
"blabla Klingon; tlhIngan-Hol bla "
"blabla Tlingit bla "
"blabla Tamashek bla "
"blabla Tonga (Nyasa) bla "
"blabla Tonga (Tonga Islands) bla "
"blabla Tok Pisin bla "
"blabla Tsimshian bla "
"blabla Tswana bla "
"blabla Tsonga bla "
"blabla Turkmen bla "
"blabla Tumbuka bla "
"blabla Tupi languages bla "
"blabla Turkish bla "
"blabla Altaic languages bla "
"blabla Tuvalu bla "
"blabla Twi bla "
"blabla Tuvinian bla "
"blabla Udmurt bla "
"blabla Ugaritic bla "
"blabla Uighur; Uyghur bla "
"blabla Ukrainian bla "
"blabla Umbundu bla "
"blabla Undetermined bla "
"blabla Urdu bla "
"blabla Uzbek bla "
"blabla Vai bla "
"blabla Venda bla "
"blabla Vietnamese bla "
"blabla Volapük bla "
"blabla Votic bla "
"blabla Wakashan languages bla "
"blabla Walamo bla "
"blabla Waray bla "
"blabla Washo bla "
"blabla Welsh bla "
"blabla Sorbian languages bla "
"blabla Walloon bla "
"blabla Wolof bla "
"blabla Kalmyk; Oirat bla "
"blabla Xhosa bla "
"blabla Yao bla "
"blabla Yapese bla "
"blabla Yiddish bla "
"blabla Yoruba bla "
"blabla Yupik languages bla "
"blabla Zapotec bla "
"blabla Blissymbols; Blissymbolics; Bliss bla "
"blabla Zenaga bla "
"blabla Standard Moroccan Tamazight bla "
"blabla Zhuang; Chuang bla "
"blabla Zande languages bla "
"blabla Zulu bla "
"blabla Zuni bla "
"blabla No linguistic content; Not applicable bla "
"blabla Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki bla "
"blabla Empty bla ";
        std::string ref_ret = 
        "aar,"
"abk,"
"ace,"
"ach,"
"ada,"
"ady,"
"afa,"
"afh,"
"afr,"
"ain,"
"aka,"
"akk,"
"alb,"
"ale,"
"alg,"
"alt,"
"amh,"
"ang,"
"anp,"
"apa,"
"ara,"
"arc,"
"arg,"
"arm,"
"arn,"
"arp,"
"art,"
"arw,"
"asm,"
"ast,"
"ath,"
"aus,"
"ava,"
"ave,"
"awa,"
"aym,"
"aze,"
"bad,"
"bai,"
"bak,"
"bal,"
"bam,"
"ban,"
"baq,"
"bas,"
"bat,"
"bej,"
"bel,"
"bem,"
"ben,"
"ber,"
"bho,"
"bih,"
"bik,"
"bin,"
"bis,"
"bla,"
"bnt,"
"bos,"
"bra,"
"bre,"
"btk,"
"bua,"
"bug,"
"bul,"
"bur,"
"byn,"
"cad,"
"cai,"
"car,"
"cat,"
"cau,"
"ceb,"
"cel,"
"cha,"
"chb,"
"che,"
"chg,"
"chi,"
"chk,"
"chm,"
"chn,"
"cho,"
"chp,"
"chr,"
"chu,"
"chv,"
"chy,"
"cmc,"
"cop,"
"cor,"
"cos,"
"cpe,"
"cpf,"
"cpp,"
"cre,"
"crh,"
"crp,"
"csb,"
"cus,"
"cze,"
"dak,"
"dan,"
"dar,"
"day,"
"del,"
"den,"
"dgr,"
"din,"
"div,"
"doi,"
"dra,"
"dsb,"
"dua,"
"dum,"
"dut,"
"dyu,"
"dzo,"
"efi,"
"egy,"
"eka,"
"elx,"
"eng,"
"enm,"
"epo,"
"est,"
"ewe,"
"ewo,"
"fan,"
"fao,"
"fat,"
"fij,"
"fil,"
"fin,"
"fiu,"
"fon,"
"fre,"
"frm,"
"fro,"
"frr,"
"frs,"
"fry,"
"ful,"
"fur,"
"gaa,"
"gay,"
"gba,"
"gem,"
"geo,"
"ger,"
"gez,"
"gil,"
"gla,"
"gle,"
"glg,"
"glv,"
"gmh,"
"goh,"
"gon,"
"gor,"
"got,"
"grb,"
"grc,"
"gre,"
"grn,"
"gsw,"
"guj,"
"gwi,"
"hai,"
"hat,"
"hau,"
"haw,"
"heb,"
"her,"
"hil,"
"him,"
"hin,"
"hit,"
"hmn,"
"hmo,"
"hrv,"
"hsb,"
"hun,"
"hup,"
"iba,"
"ibo,"
"ice,"
"ido,"
"iii,"
"ijo,"
"iku,"
"ile,"
"ilo,"
"ina,"
"inc,"
"ind,"
"ine,"
"inh,"
"ipk,"
"ira,"
"iro,"
"ita,"
"jav,"
"jbo,"
"jpn,"
"jpr,"
"jrb,"
"kaa,"
"kab,"
"kac,"
"kal,"
"kam,"
"kan,"
"kar,"
"kas,"
"kau,"
"kaw,"
"kaz,"
"kbd,"
"kha,"
"khi,"
"khm,"
"kho,"
"kik,"
"kin,"
"kir,"
"kmb,"
"kok,"
"kom,"
"kon,"
"kor,"
"kos,"
"kpe,"
"krc,"
"krl,"
"kro,"
"kru,"
"kua,"
"kum,"
"kur,"
"kut,"
"lad,"
"lah,"
"lam,"
"lao,"
"lat,"
"lav,"
"lez,"
"lim,"
"lin,"
"lit,"
"lol,"
"loz,"
"ltz,"
"lua,"
"lub,"
"lug,"
"lui,"
"lun,"
"luo,"
"lus,"
"mac,"
"mad,"
"mag,"
"mah,"
"mai,"
"mak,"
"mal,"
"man,"
"mao,"
"map,"
"mar,"
"mas,"
"may,"
"mdf,"
"mdr,"
"men,"
"mga,"
"mic,"
"min,"
"mis,"
"mkh,"
"mlg,"
"mlt,"
"mnc,"
"mni,"
"mno,"
"moh,"
"mon,"
"mos,"
"mul,"
"mun,"
"mus,"
"mwl,"
"mwr,"
"myn,"
"myv,"
"nah,"
"nai,"
"nap,"
"nau,"
"nav,"
"nbl,"
"nde,"
"ndo,"
"nds,"
"nep,"
"new,"
"nia,"
"nic,"
"niu,"
"nno,"
"nob,"
"nog,"
"non,"
"nor,"
"nqo,"
"nso,"
"nub,"
"nwc,"
"nya,"
"nym,"
"nyn,"
"nyo,"
"nzi,"
"oci,"
"oji,"
"ori,"
"orm,"
"osa,"
"oss,"
"ota,"
"oto,"
"paa,"
"pag,"
"pal,"
"pam,"
"pan,"
"pap,"
"pau,"
"peo,"
"per,"
"phi,"
"phn,"
"pli,"
"pol,"
"pon,"
"por,"
"pra,"
"pro,"
"pus,"
"qaa-qtz,"
"que,"
"raj,"
"rap,"
"rar,"
"roa,"
"roh,"
"rom,"
"rum,"
"run,"
"rup,"
"rus,"
"sad,"
"sag,"
"sah,"
"sai,"
"sal,"
"sam,"
"san,"
"sas,"
"sat,"
"scn,"
"sco,"
"sel,"
"sem,"
"sga,"
"sgn,"
"shn,"
"sid,"
"sin,"
"sio,"
"sit,"
"sla,"
"slo,"
"slv,"
"sma,"
"sme,"
"smi,"
"smj,"
"smn,"
"smo,"
"sms,"
"sna,"
"snd,"
"snk,"
"sog,"
"som,"
"son,"
"sot,"
"spa,"
"srd,"
"srn,"
"srp,"
"srr,"
"ssa,"
"ssw,"
"suk,"
"sun,"
"sus,"
"sux,"
"swa,"
"swe,"
"syc,"
"syr,"
"tah,"
"tai,"
"tam,"
"tat,"
"tel,"
"tem,"
"ter,"
"tet,"
"tgk,"
"tgl,"
"tha,"
"tib,"
"tig,"
"tir,"
"tiv,"
"tkl,"
"tlh,"
"tli,"
"tmh,"
"tog,"
"ton,"
"tpi,"
"tsi,"
"tsn,"
"tso,"
"tuk,"
"tum,"
"tup,"
"tur,"
"tut,"
"tvl,"
"twi,"
"tyv,"
"udm,"
"uga,"
"uig,"
"ukr,"
"umb,"
"und,"
"urd,"
"uzb,"
"vai,"
"ven,"
"vie,"
"vol,"
"vot,"
"wak,"
"wal,"
"war,"
"was,"
"wel,"
"wen,"
"wln,"
"wol,"
"xal,"
"xho,"
"yao,"
"yap,"
"yid,"
"yor,"
"ypk,"
"zap,"
"zbl,"
"zen,"
"zgh,"
"zha,"
"znd,"
"zul,"
"zun,"
"zxx,"
"zza,"
"empty,";
        ref_ret.pop_back();
        std::string ret;
        c_str p = (c_str)test;
        while(lang2code(p, ret));
        REQUIRE(ret == ref_ret);
    }
}
